import type { ComputeCardSpec } from '../entities/ComputeCard';

/**
 * 计算卡规格表
 *
 * 新增型号只需在此添加条目，并在 config/resources.ts 注册对应资源。
 * 系统会自动处理采购、交付、磨损、算力汇总、电力消耗。
 */
export const COMPUTE_CARD_SPECS: ComputeCardSpec[] = [
  // ===== 现有型号（补全新字段） =====
  {
    resourceId: 'compute_a100',
    name: 'A100 80GB',
    tflopsPerCard: 624,
    powerPerCard: 0.4,
    maxPowerDrawKW: 0.4,
    unitCost: 10_000,
    deliveryDays: 3,
    wearPerDay: 0.0008,
    memoryGB: 80,
    memoryBandwidth: 1935,
    interconnect: 'NVLink3',
    nvlinkBandwidth: 600,
    supportsFP8: false,
    supportsFP4: false,
    sparsityAccel: true,
    recommendedRole: 'both',
  },
  {
    resourceId: 'compute_h100',
    name: 'H100 80GB',
    tflopsPerCard: 1979,
    powerPerCard: 0.7,
    maxPowerDrawKW: 0.7,
    unitCost: 30_000,
    deliveryDays: 7,
    wearPerDay: 0.0005,
    memoryGB: 80,
    memoryBandwidth: 3350,
    interconnect: 'NVLink4',
    nvlinkBandwidth: 900,
    fp8Tflops: 3958,
    supportsFP8: true,
    supportsFP4: false,
    sparsityAccel: true,
    recommendedRole: 'training',
  },

  // ===== 新增型号 =====
  {
    resourceId: 'compute_a100_40g',
    name: 'A100 40GB',
    tflopsPerCard: 312,
    powerPerCard: 0.3,
    maxPowerDrawKW: 0.3,
    unitCost: 6_000,
    deliveryDays: 2,
    wearPerDay: 0.001,
    memoryGB: 40,
    memoryBandwidth: 1555,
    interconnect: 'NVLink3',
    nvlinkBandwidth: 600,
    supportsFP8: false,
    supportsFP4: false,
    sparsityAccel: true,
    recommendedRole: 'both',
  },
  {
    resourceId: 'compute_h200',
    name: 'H200 141GB',
    tflopsPerCard: 1979,
    powerPerCard: 0.7,
    maxPowerDrawKW: 0.75,
    unitCost: 40_000,
    deliveryDays: 10,
    wearPerDay: 0.0004,
    memoryGB: 141,
    memoryBandwidth: 4800,
    interconnect: 'NVLink4',
    nvlinkBandwidth: 900,
    fp8Tflops: 3958,
    supportsFP8: true,
    supportsFP4: false,
    sparsityAccel: true,
    recommendedRole: 'training',
  },
  {
    resourceId: 'compute_b200',
    name: 'B200 192GB',
    tflopsPerCard: 4500,
    powerPerCard: 1.0,
    maxPowerDrawKW: 1.2,
    unitCost: 45_000,
    deliveryDays: 14,
    wearPerDay: 0.0003,
    memoryGB: 192,
    memoryBandwidth: 8000,
    interconnect: 'NVLink5',
    nvlinkBandwidth: 1800,
    fp8Tflops: 9000,
    supportsFP8: true,
    supportsFP4: true,
    sparsityAccel: true,
    recommendedRole: 'training',
  },
  {
    resourceId: 'compute_gb300',
    name: 'GB300 288GB',
    tflopsPerCard: 7500,
    powerPerCard: 1.5,
    maxPowerDrawKW: 1.8,
    unitCost: 75_000,
    deliveryDays: 21,
    wearPerDay: 0.0002,
    memoryGB: 288,
    memoryBandwidth: 13000,
    interconnect: 'NVLink6',
    nvlinkBandwidth: 3600,
    fp8Tflops: 15000,
    supportsFP8: true,
    supportsFP4: true,
    sparsityAccel: true,
    recommendedRole: 'training',
  },
  {
    resourceId: 'compute_l40s',
    name: 'L40S 48GB',
    tflopsPerCard: 733,
    powerPerCard: 0.3,
    maxPowerDrawKW: 0.35,
    unitCost: 8_000,
    deliveryDays: 3,
    wearPerDay: 0.0006,
    memoryGB: 48,
    memoryBandwidth: 864,
    interconnect: 'PCIe5',
    nvlinkBandwidth: 0,
    fp8Tflops: 733,
    supportsFP8: true,
    supportsFP4: false,
    sparsityAccel: false,
    recommendedRole: 'inference',
  },
];

/** 按 resourceId 查找卡规格 */
const SPEC_MAP = new Map(COMPUTE_CARD_SPECS.map((s) => [s.resourceId, s]));

/** 按 resourceId 获取规格，找不到返回 undefined */
export function getCardSpec(resourceId: string): ComputeCardSpec | undefined {
  return SPEC_MAP.get(resourceId);
}
